/*
 * script.js — RETIRED
 *
 * This file has been split into focused modules in the js/ directory:
 *
 *   js/loader.js  — Loading screen, typing animation, video fade, learn-page word animation
 *   js/popup.js   — Timer popup, waitlist/download form submission
 *   js/ui.js      — Hamburger menu, sticky header scroll, smooth scroll
 *
 * Do not edit this file. Edit the appropriate module in js/ instead.
 */
